{
 "title": "OVS-DPDK",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Datapath", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RX packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_rx_packets_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "TX packet rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_tx_packets_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RX packet drop rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_rx_dropped_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "TX packet drop rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_tx_dropped_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "RX throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_rx_bytes_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "TX throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ovs_dpdk_telemetry_datapath_port_tx_bytes_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "PMD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets receive rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ovs_dpdk_telemetry_pmd_threads_packets_received_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Processing cycles %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "increase(ovs_dpdk_telemetry_pmd_threads_processing_cycles_total[$__rate_interval])/(increase(ovs_dpdk_telemetry_pmd_threads_processing_cycles_total[$__rate_interval])+increase(ovs_dpdk_telemetry_pmd_threads_idle_cycles_total[$__rate_interval]))*100"
      }
     ]
    },
    {
     "title": "Average processing cycles per packet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "c/p" } },
     "targets": [
      {
       "expr": "ovs_dpdk_telemetry_pmd_threads_avg_processing_cycles_per_packet"
      }
     ]
    },
    {
     "title": "Average cycles per packet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "c/p" } },
     "targets": [
      {
       "expr": "ovs_dpdk_telemetry_pmd_threads_avg_cycles_per_packet"
      }
     ]
    }
   ]
  }
 ]
}